name: CI

on: [push, pull_request]
# on: workflow_dispatch

jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v3

#     - name: Print Hello World
#       run: |
#         echo "hello world"
#         echo "test123" > doc/test.txt
#         ls .
#     - run: cmake --version

#     - name: upload artifacts
#       uses: actions/upload-artifact@v3
#       with:
#         name: dist-without-markdown
#         path: |
#           doc
#           !doc/**/*.md
#         retention-days: 5
        
  build_toolchain_cache:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Restore Cached Toolchain
      id: Restore_Cached_Toolchain
      uses: actions/cache@v3
      with:
        path: nds32le-elf-mculib-v5f
        key: ${{ runner.os }}-nds32le-elf-mculib-v5f-${{ hashFiles('./.github/nds_toolchain_version') }}
        restore-keys: |
          ${{ runner.os }}-nds32le-elf-mculib-v5f-

    - run: |
        echo $steps.Restore_Cached_Toolchain.outputs.cache-hit
     
    - if: ${{ steps.Restore_Cached_Toolchain.outputs.cache-hit != 'true' }}
      name: download and decompression toolchain
      run: |
        wget -O riscv.tar https://github.com/andestech/Andes-Development-Kit/releases/download/ast-v3_2_3-release-linux/nds32le-elf-mculib-v5f.txz
        tar xf riscv.tar
        if [ $? != 0 ]; then
          echo "download toolchain fail"
          exit 1
        fi
        
        
    # - name: download and decompression toolchain
    #   run: |
    #     echo "download and decompression toolchain"
    #     # # Your build steps here
    #     # pwd
    #     # ls .
    #     # wget -O riscv.tar https://github.com/andestech/Andes-Development-Kit/releases/download/ast-v3_2_3-release-linux/nds32le-elf-mculib-v5f.txz
    #     # ls .
    #     # tar xf riscv.tar
    #     # ls .
    #     # cd nds32le-elf-mculib-v5f
    #     # ls .

    - if: ${{ steps.Restore_Cached_Toolchain.outputs.cache-hit != 'true' }}
      name: Cache Toolchain
      uses: actions/cache@v3
      with:
        path: nds32le-elf-mculib-v5f
        key: ${{ runner.os }}-nds32le-elf-mculib-v5f-${{ hashFiles('./.github/nds_toolchain_version') }}

    - name: convert cdt2cmake
      run: |
        echo "convert cdt2cmkae"

    - name: cmake build
      run: |
        echo "cmake building..."
  # use_cache:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v3

  #   - run : ls .
    
  #   - name: Restore Cached Toolchain
  #     uses: actions/cache@v3
  #     with:
  #       path: nds32le-elf-mculib-v5f
  #       key: ${{ runner.os }}-nds32le-elf-mculib-v5f-${{ hashFiles('./.github/nds_toolchain_version') }}
  #       restore-keys: |
  #         ${{ runner.os }}-nds32le-elf-mculib-v5f-

  #   - name: Use Cached Toolchain
  #     run: |
  #       # Your steps that use the cached toolchain
  #       echo "Using cached toolchain..."
  #       ls .
  #       ls nds32le-elf-mculib-v5f
